name: package release
on:
  push:
    tags:
      - "v[0-9].[0-9].[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
      runs-on: ubuntu-latest
      steps:
          - name: checkout
            uses: actions/checkout@v3
          - name: set up docker builx
            uses: docker/setup-buildx-action@v2
          - name: cache docker layers
            uses: actions/cache@v3
            with:
                path: /tmp/.buildx-cache
                key: ${{ runner.os }}-buildx-${{ github.sha }}
                restore-keys: |
                    ${{ runner.os }}-buildx-
          - name: prepare build args
            id: prepare_build_arg
            run: |
                CURRENT_TAG=${GITHUB_REF#refs/tags/}
                echo "CURRENT_TAG=${CURRENT_TAG}" >> $GITHUB_OUTPUT
          - name: login to dockerhub
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: build and push docker image to dockerhub
            uses: docker/build-push-action@v3
            with:
                push: true
                tags: tamago0224/rest-app:${{ steps.prepare_build_arg.outputs.CURRENT_TAG }}
